parameters:
#    olix_test.example.class: Olix\TestBundle\Example

services:
#    olix_test.example:
#        class: %olix_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
